interface Proxy {
    type: string;
    status: string;
    redirect_enabled: boolean;
    last_saved_settings: string;
    last_applied_settings: string;
    force_stop: boolean;
  }
  
  interface ServerSettings {
    id: number;
    is_swarm_manager: boolean;
    is_jump_server: boolean;
    is_build_server: boolean;
    is_reachable: boolean;
    is_usable: boolean;
    server_id: number;
    created_at: string;
    updated_at: string;
    wildcard_domain: string;
    is_cloudflare_tunnel: boolean;
    is_logdrain_newrelic_enabled: boolean;
    logdrain_newrelic_license_key: string | null;
    logdrain_newrelic_base_uri: string | null;
    is_logdrain_highlight_enabled: boolean;
    logdrain_highlight_project_id: string | null;
    is_logdrain_axiom_enabled: boolean;
    logdrain_axiom_dataset_name: string | null;
    logdrain_axiom_api_key: string | null;
    is_swarm_worker: boolean;
    is_logdrain_custom_enabled: boolean;
    logdrain_custom_config: string | null;
    logdrain_custom_config_parser: string | null;
    concurrent_builds: number;
    dynamic_timeout: number;
    force_disabled: boolean;
    is_metrics_enabled: boolean;
    generate_exact_labels: boolean;
    force_docker_cleanup: boolean;
    docker_cleanup_frequency: string;
    docker_cleanup_threshold: number;
    server_timezone: string;
    delete_unused_volumes: boolean;
    delete_unused_networks: boolean;
    is_sentinel_enabled: boolean;
    sentinel_token: string;
    sentinel_metrics_refresh_rate_seconds: number;
    sentinel_metrics_history_days: number;
    sentinel_push_interval_seconds: number;
    sentinel_custom_url: string;
    server_disk_usage_notification_threshold: number;
    is_sentinel_debug_enabled: boolean;
    server_disk_usage_check_frequency: string;
  }
  
  interface Server {
    id: number;
    uuid: string;
    name: string;
    description: string;
    ip: string;
    port: number;
    user: string;
    team_id: number;
    private_key_id: number;
    proxy: Proxy;
    created_at: string;
    updated_at: string;
    unreachable_notification_sent: boolean;
    unreachable_count: number;
    high_disk_usage_notification_sent: boolean;
    log_drain_notification_sent: boolean;
    swarm_cluster: string | null;
    validation_logs: string | null;
    sentinel_updated_at: string;
    deleted_at: string | null;
    is_coolify_host: boolean;
    settings: ServerSettings;
  }
  
  interface Destination {
    id: number;
    name: string;
    uuid: string;
    network: string;
    server_id: number;
    created_at: string;
    updated_at: string;
    server: Server;
  }
  
  export interface Application {
    uuid: string;
    name: string;
    additional_networks_count: number;
    additional_servers: any[];
    additional_servers_count: number;
    base_directory: string;
    build_command: string | null;
    build_pack: string;
    compose_parsing_version: string;
    config_hash: string;
    custom_docker_run_options: string | null;
    custom_healthcheck_found: boolean;
    custom_nginx_configuration: string;
    deleted_at: string | null;
    description: string | null;
    destination: Destination;
    destination_id: number;
    destination_type: string;
    docker_compose_custom_build_command: string | null;
    docker_compose_custom_start_command: string;
    docker_compose_domains: string;
    docker_compose_location: string;
    docker_registry_image_name: string | null;
    docker_registry_image_tag: string | null;
    dockerfile_location: string;
    dockerfile_target_build: string | null;
    environment_id: number;
    fqdn: string | null;
    git_branch: string;
    git_commit_sha: string;
    git_full_url: string | null;
    git_repository: string;
    health_check_enabled: boolean;
    health_check_host: string;
    health_check_interval: number;
    health_check_method: string;
    health_check_path: string;
    health_check_port: number | null;
    health_check_response_text: string | null;
    health_check_retries: number;
    health_check_return_code: number;
    health_check_scheme: string;
    health_check_start_period: number;
    health_check_timeout: number;
    install_command: string | null;
    laravel_through_key: number;
    last_online_at: string;
    limits_cpu_shares: number;
    limits_cpus: string;
    limits_cpuset: string | null;
    limits_memory: string;
    limits_memory_reservation: string;
    limits_memory_swap: string;
    limits_memory_swappiness: number;
    ports_exposes: string;
    ports_mappings: string | null;
    post_deployment_command: string | null;
    post_deployment_command_container: string | null;
    pre_deployment_command: string | null;
    pre_deployment_command_container: string | null;
    preview_url_template: string;
    publish_directory: string;
    redirect: string;
    repository_project_id: number;
    server_status: boolean;
    source_id: number;
    source_type: string;
    start_command: string | null;
    static_image: string;
    status: string;
    swarm_placement_constraints: string | null;
    swarm_replicas: number;
    watch_paths: string | null;
    created_at: string;
    updated_at: string;
  }